# Generated by Django 5.0.7 on 2024-10-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='class_rooms',
        ),
        migrations.RemoveField(
            model_name='school',
            name='grades',
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(to='school.student'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ManyToManyField(to='school.teacher'),
        ),
        migrations.AddField(
            model_name='grade',
            name='class_rooms',
            field=models.ManyToManyField(to='school.classroom'),
        ),
        migrations.AddField(
            model_name='school',
            name='grades',
            field=models.ManyToManyField(to='school.grade'),
        ),
    ]
