# Generated by Django 5.0.7 on 2024-10-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('student_id', models.IntegerField(max_length=8, null=True)),
                ('has_dorm', models.BooleanField(null=True)),
                ('grade', models.CharField(max_length=15, null=True)),
                ('education_type', models.CharField(max_length=20, null=True)),
                ('major', models.CharField(max_length=10, null=True)),
                ('sub_major', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True)),
                ('description', models.TextField(null=True)),
                ('gender', models.CharField(max_length=15, null=True)),
                ('year_of_foundation', models.DateField(null=True)),
                ('school_type', models.CharField(max_length=15, null=True)),
                ('education_level', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HighStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('has_school_bus', models.BooleanField(null=True)),
                ('grade', models.CharField(max_length=2, null=True)),
                ('major', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('salary_per_day', models.IntegerField(null=True)),
                ('working_days', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='grades',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Elementary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2, null=True)),
                ('class_room', models.ManyToManyField(null=True, to='school.classroom')),
                ('students', models.ManyToManyField(null=True, to='school.student')),
                ('teachers', models.ManyToManyField(null=True, to='school.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='FirstHigh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2, null=True)),
                ('class_room', models.ManyToManyField(null=True, to='school.classroom')),
                ('students', models.ManyToManyField(null=True, to='school.student')),
                ('teachers', models.ManyToManyField(null=True, to='school.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20, null=True)),
                ('grade', models.CharField(max_length=20, null=True)),
                ('major', models.CharField(max_length=20, null=True)),
                ('sub_major', models.CharField(max_length=20, null=True)),
                ('class_rooms', models.ManyToManyField(null=True, to='school.classroom')),
                ('students', models.ManyToManyField(null=True, to='school.student')),
                ('masters', models.ManyToManyField(null=True, to='school.master')),
            ],
        ),
        migrations.CreateModel(
            name='SecondHigh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2, null=True)),
                ('major', models.CharField(max_length=15, null=True)),
                ('class_room', models.ManyToManyField(null=True, to='school.classroom')),
                ('students', models.ManyToManyField(null=True, to='school.student')),
                ('teachers', models.ManyToManyField(null=True, to='school.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
